spring:
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:file:~/test
      username: sa
      password:
      driverClassName: org.h2.Driver
      
      
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: ${cognito-client-id}
            client-secret: ${cognito-client-secret}
        provider:
          cognito: 
            issuer-uri: ${cognito-issuer-uri}
            
